// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHAsMyOhUd_DfwfCOaqWGPD1X-XfoH8RI',
    appId: '1:922418710491:web:b691dfe0b6ce3b37d589fe',
    messagingSenderId: '922418710491',
    projectId: 'login-9dc05',
    authDomain: 'login-9dc05.firebaseapp.com',
    storageBucket: 'login-9dc05.appspot.com',
    measurementId: 'G-3CGBKS2SF0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALsfS65es5_MbSyDIuhnNzZTstUWo_GbQ',
    appId: '1:922418710491:android:4435ed4713251f8cd589fe',
    messagingSenderId: '922418710491',
    projectId: 'login-9dc05',
    storageBucket: 'login-9dc05.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX3VIG0vshvgwP7Exhfh1OHTDY4u9uP8w',
    appId: '1:922418710491:ios:2299c5cd6a2a463cd589fe',
    messagingSenderId: '922418710491',
    projectId: 'login-9dc05',
    storageBucket: 'login-9dc05.appspot.com',
    iosClientId: '922418710491-kojj66oe6h0fcjapihf2jc8jbtkq2ofm.apps.googleusercontent.com',
    iosBundleId: 'com.example.blocFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX3VIG0vshvgwP7Exhfh1OHTDY4u9uP8w',
    appId: '1:922418710491:ios:c9a5d090f6179af0d589fe',
    messagingSenderId: '922418710491',
    projectId: 'login-9dc05',
    storageBucket: 'login-9dc05.appspot.com',
    iosClientId: '922418710491-651ejpu3oo39vpamb45ouursmir2doup.apps.googleusercontent.com',
    iosBundleId: 'com.example.blocFirebase.RunnerTests',
  );
}
